### ISSUE TITLE
The value of  'loss_rel' is nan

### ISSUE THREAD

**Issue by xcppy** [YiwuZhong/SGG_from_NLS#1]
Hi, thanks for your released project. I have tried to run your code in the setting of  'Weakly_Uniter',  but why does the value of 'loss_rel' turn to be 'nan' after 500 iters?

**Comment by YiwuZhong** [comment]
Thanks for your interests on this project! This is common when using Transformer as model architecture. One of the solution is to lower the learning rate. You can try lower the default learning rate by multiplying a factor of 0.5 or 0.1.
