### ISSUE TITLE
use the code for custom images

### ISSUE THREAD

**Issue by DeepaliVerma** [YiwuZhong/SGG_from_NLS#3]
Sir, how can I use this code to predict scene graphs on random images rather than the dataset images.

**Comment by YiwuZhong** [comment]
Thanks for your interest in our paper! To run on custom images, before using the SGG models, the first step is to detect objects and extract their features. 

In most of our experiments, following [VSPNet](https://github.com/alirezazareian/vspnet), we used [the object detector trained on OpenImage-V4 from Tensorflow](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1_detection_zoo.md#open-images-trained-models). [This post](https://gist.github.com/markdtw/02ece6b90e75832bd44787c03a664e8d#gistcomment-3444976) might be useful for region feature extraction. Or the other way, you can use [the object detector trained on Visual Genome](https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch#pretrained-models). This detector was used in our fully supervised experiment and can be combined with our trained model `Sup_OnlineDetector_Uniter` in the README. The command can be referred to [SGDet on Custom Images](https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch#sgdet-on-custom-images).

**Comment by YiwuZhong** [comment]
There is a [new update](https://github.com/YiwuZhong/SGG_from_NLS#pretrained-object-detector) about extracting region features using Tensorflow Object Detection API. If you're interested in using Tensorflow API, the discussion in post #5 might be helpful.
