### ISSUE TITLE
The object features from the pretrained detector on OpenImages

### ISSUE THREAD

**Issue by Kenneth-Wong** [YiwuZhong/SGG_from_NLS#5]
Noticed that The pretrained detector on OpenImages you applied is based on Tensorflow. However, this repo is based on pytorch. Are the object features directly applicable?

**Comment by YiwuZhong** [comment]
Thanks for your interests. The region features were extracted as offline files (eg, numpy array). These features become the inputs of models and should be compatible with any deep learning framework, including Pytorch.

**Comment by Kenneth-Wong** [comment]
Thanks. Would you mind providing the script for extracting the features and bounding boxes, etc.? Or can you explain which variables should be extracted using Tensorflow detector APIs?

**Comment by Kenneth-Wong** [comment]
As I want to generate the SG on custom images, I have to configure the detector. I want to use the pretrained detector on OpenImages.  I found two methods, [tensorflow/object_detection](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/object_detection_tutorial.ipynb) and [WSSGG](https://github.com/yekeren/WSSGG/blob/master/dataset-tools/create_coco_frcnn_proposals.py). However, the first one cannnot extract the features, and the features from the second one do not match with those you provided (on MSCOCO).  Would you explain which method you use?

**Comment by YiwuZhong** [comment]
The script used for region feature extraction is now uploaded in [preprocess/README.md](https://github.com/YiwuZhong/SGG_from_NLS/tree/main/preprocess). The reasons why features are different across repos might include: which layer to extract region features (see [extract_oid_features.py](https://github.com/YiwuZhong/SGG_from_NLS/blob/main/preprocess/extract_oid_features.py)), hyperparameter of the detector ([pipeline.config](https://github.com/YiwuZhong/SGG_from_NLS/blob/main/preprocess/pipeline.config)).

**Comment by Kenneth-Wong** [comment]
Wow, cool! I successfully got them. Thanks!
