### ISSUE TITLE
can you upload the code to get the obj_norn and predicate_norn from caption for vg/coco/cc dataset?

### ISSUE THREAD

**Issue by ZHUXUHAN** [YiwuZhong/SGG_from_NLS#6]
Dear sir,
I have seen the detailed process, but I have not seen the code of getting obj_norn and predicate_norn from caption.Would you like to upload the code of this part.

**Comment by YiwuZhong** [comment]
@ZHUXUHAN Not totally sure what "obj_norn" and "predicate_norn" mean. If you're saying how to extract nouns and verbs from captions, we use this [scene graph parser](https://github.com/vacancy/SceneGraphParser), as demonstrated at Triplet Parsing and Filtering of Section 3.2 in our paper.

**Comment by ZHUXUHAN** [comment]
Ok, thanks!
