### ISSUE TITLE
Run the SGG model on a set of custom images for inference

### ISSUE THREAD

**Issue by prateksha** [YiwuZhong/SGG_from_NLS#7]
Hi, I have been able to run the object detector - pretrained faster rcnn and obtain the object detections. However, I am not sure on how to get the scene graph predictions using any of the pretrained scene graph generation models - ex: Language_CC-COCO_Uniter models on the custom images. Please let me know the steps to do this

According to my understanding of the paper, the proposed model does not need the image caption during inference. However, I would like to see the results by passing (image + caption) as input during inference. Please let me know how this can be done.

Thanks in advance. Looking forward for your response.

**Comment by YiwuZhong** [comment]
@prateksha Thanks for your interests. Our model should be able to inference on any images, as long as the object detections results are obtained before hand. Unfortunately, this functionality hasn't been supported yet. I'd recommend to (1) modify the [data loader](https://github.com/YiwuZhong/SGG_from_NLS/blob/ef81464b29a8ce52917445ec4b93b4b66e927916/maskrcnn_benchmark/data/datasets/visual_genome.py#L158) for your detection results of custom images, and (2) find the predictions in [relation head](https://github.com/YiwuZhong/SGG_from_NLS/blob/ef81464b29a8ce52917445ec4b93b4b66e927916/maskrcnn_benchmark/modeling/roi_heads/relation_head/inference.py#L333).

Our model was designed for scene graph generation. This task takes inputs as an image and its detected objects, and outputs a localized scene graph. It is interesting to see whether an additional input, such as a caption, can provide hints/helps for scene graph generation. One possibility is that, once you get scene graph prediction from our model, you could further filter the scene graph prediction using caption. This can be done by using the nouns from captions to only keep the sub-graphs that involve these nouns.

**Comment by prateksha** [comment]
@YiwuZhong Thank you for your detailed reply. Could you please tell me the exact modifications that need to be made in the [data loader](https://github.com/YiwuZhong/SGG_from_NLS/blob/ef81464b29a8ce52917445ec4b93b4b66e927916/maskrcnn_benchmark/data/datasets/visual_genome.py#L158) to obtain results on a set of custom images stored in a directory `data/images`?

**Comment by YiwuZhong** [comment]
@prateksha You might want to look into the data loader a bit. There should be sufficient comments for you to understand what has been loaded. For example, you can replace the [region features](https://github.com/YiwuZhong/SGG_from_NLS/blob/ef81464b29a8ce52917445ec4b93b4b66e927916/maskrcnn_benchmark/data/datasets/visual_genome.py#L197) using yours.
