### ISSUE TITLE
AttributeError: module 'torchvision' has no attribute 'datasets'

### ISSUE THREAD

**Issue by PrimoWW** [YiwuZhong/SGG_from_NLS#8]
File "/home/xxx/icme/sgg_from_nls/maskrcnn_benchmark/data/datasets/coco.py", line 39, in <module>
    class COCODataset(torchvision.datasets.coco.CocoDetection):
AttributeError: module 'torchvision' has no attribute 'datasets'

I dont know why it cannot import cocodataset

**Comment by YiwuZhong** [comment]
It seems to be the error from torchvision. How about trying the solution from forum (e.g., [this solution](https://discuss.pytorch.org/t/module-torchvision-has-no-attribute-datasets/16225/5)).
