### ISSUE TITLE
Missing input data

### ISSUE THREAD

**Issue by JingyuLi-code** [YiwuZhong/SGG_from_NLS#9]
Hi, Yiwu:
parse_captions.py have no input_file , can you provide it? 

input_file = 'vg_caption_triplet_POS_dict.pkl'  # 'COCO_caption_triplet_POS_dict.pkl' #'flickr30k_caption_triplet_POS_dict.pkl' #

**Comment by YiwuZhong** [comment]
@JingyuLi-code This script parses triplets from input sentences. You don't necessarily require `.pkl` files I wrote there. The only thing you need is a file containing captions. The caption data can be downloaded from the respective dataset website.
